name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  retry:
    description: 'Should Retry'
    required: false
  retry_timeout:
    description: 'Should Retry Timeout (in seconds)'
    required: false
  retry_interval:
    description: 'Retry Interval (in seconds)'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
